import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/molecul/navbar/Navbar';
import { RoutesUtils } from '@/utils/Route';
import Provider from '@/provider/Provider';
import Head from 'next/head';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', sizes: '32x32', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gray-50`}>
        <Head>
          <link rel="icon" href="/favicon.ico"></link>
        </Head>
        <Navbar data={RoutesUtils} />

        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
